### ISSUE TITLE
How to watch the Acquisition Completion (Sequence Queue)

### ISSUE THREAD

**Issue by heejongkim** [thermofisherlsms/xcalibur-workbench#2]
Hello,

Again, thanks for sharing this great interface via Lua.
If I remember correctly about the conversation with Michael W. Senko during the ASMS 2016 Poster session, there is a way to watch the sequence queue and launch a script when the acquisition finishes but I cannot find a document about how to access/talk to a machine associated software (or subset of it), such as Xcalibur (Acquisition Queue).
Can you please briefly share the idea how to approach this with xcalibur-workbench?
Thank you.
-"Hee Jong" Kim

**Comment by MichaelSenko** [comment]
Ideally, you want to interface with the Xcalibur Acquisition Server.  There is a COM object 'AcqServer.AcqInterfaceSupport1' that you can either wrap with a Lua interface, or you might be able to call directly using LuaCOM.  We've done the former and know it will work, but we've not tried the latter.

Possibly simpler, but less flexible, is to modify ThermoRawFile.dll so that it exposes the InAcquisition() method of MSFileReader.  If you sit and watch this, it should tell you when that specific file has completed acquisition.

Thanks
Mike

**Comment by dbaileychess** [comment]
The InAcquisition() flag is already exposed in the Lua Raw File. See:
https://github.com/thermofisherlsms/lua-raw-file/blob/master/inc/RawFile.h#L173

Derek

**Comment by heejongkim** [comment]
Thank you for all the suggestions.
Because I couldn't find a Xcalibur Acquisition Server related document from anywhere, I looked into InAcquisition() method and it seems just enough for my personal purpose: automation of raw file conversion and data analysis pipeline initiation with it.
Because of InAcquisition, I realized that I had another question related to that but not directly related to this thread so I will open up the new issue.
Again, thank you for your suggestions.

Best,
Hee Jong
